name: Run YLJC

on:
  schedule:
    - cron: '*/30 * * * *'  # 每半小时触发一次
  workflow_dispatch:  # 也可以手动触发

jobs:
  run-YLJC:
    runs-on: macos-latest  # 使用 macOS 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium webdriver-manager

      - name: Run YLJC
        env:
          BARK_API_KEY: ${{ secrets.BARK_API_KEY }}
          TRAFFIC_API_URL: ${{ secrets.TRAFFIC_API_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          PLAN_URL: ${{ secrets.PLAN_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python YLJC.py
