name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium webdriver-manager

      # 使用环境变量传递敏感信息
      - name: Run the script
        env:
          BARK_API_KEY: ${{ secrets.BARK_API_KEY }}
          TRAFFIC_API_URL: ${{ secrets.TRAFFIC_API_URL }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          PLAN_URL: ${{ secrets.PLAN_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python YLJC.py
