name: Data Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次，UTC时间

jobs:
  run-data-checker:
    runs-on: macos-latest  # 你也可以选择 ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests

    - name: Run data checker
      run: |
        python YLJC.py
